//----------------------------------------------------------
// <auto-generated>
// -This code was generated.
// -Changes to this file may cause incorrect behavior.
// -will be lost if the code is regenerated.
// <auto-generated/>
//----------------------------------------------------------
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using TEngine;
using Cysharp.Threading.Tasks;

namespace GameLogic
{
	[Window(UILayer.UI, location : "MainUI")]
	public partial class MainUI : UIWindow
	{
        private partial void OnClick_StartBtn()
        {
            ModuleSystem.GetModule<ISceneModule>().LoadSceneAsync("GameScene").Forget();
        }

		private partial void OnClick_QuitBtn()
        {
#if UNITY_EDITOR
            UnityEditor.EditorApplication.isPlaying = false;
#else
#endif
            Application.Quit();
            
        }
	}
}
