//----------------------------------------------------------
// <auto-generated>
// -This code was generated.
// -Changes to this file may cause incorrect behavior.
// -will be lost if the code is regenerated.
// <auto-generated/>
//----------------------------------------------------------
using Cysharp.Threading.Tasks;
using TEngine;
using TMPro;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

namespace GameLogic
{
    [Window(UILayer.UI, location: "MainUI")]
    public partial class MainUI : UIWindow
    {
        private partial void OnClick_StartBtn()
        {
            // 通过状态机请求进入游戏
            HotFixHFSMModule.Instance?.RequestEnterGame();
            // 加载游戏场景
            ModuleSystem.GetModule<ISceneModule>().LoadSceneAsync("GameScene");
        }

        private partial void OnClick_QuitBtn()
        {
#if UNITY_EDITOR
            UnityEditor.EditorApplication.isPlaying = false;
#else
#endif
            Application.Quit();
        }
    }
    public class MainMenuState : LeafState<HFContext>
    {
        protected override void OnEnter(HFContext ctx)
        {
            Debug.Log("进入 MainMenuState（主菜单）");
            // 清除转换标志
            ctx.WantEnterGame = false;

            // 显示主菜单 UI
            GameModule.UI.ShowUIAsync<MainUI>();
        }

        protected override void OnExit(HFContext ctx)
        {
            Debug.Log("退出 MainMenuState");
            // 隐藏主菜单 UI
            GameModule.UI.CloseUI<MainUI>();
        }

        protected override void OnUpdate(HFContext ctx)
        {
            
        }
    }
}
